name: alethic-ism-core
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - pyyaml
  - pydantic
  - restrictedpython
  - nats-py
  - redis-py
  - mako
  - pytorch::pytorch
