[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "alethic-processor"
version = "0.2.0"
description = "Instruction-Based State Machine (Core)"
dependencies = [
    "python-dotenv",
    "pyyaml",
    "pydantic"
]
