key_definitions:
  - "animal"
  - "perspective_index"
  - "query_template_index"
  - "evaluation_perspective_index"

additional_columns:
  function:
    - name: "evaluation_model_name"
      value: "state.config.model_name"
      data_type: "str"
      null: False
      max_length: 255

    - name: "evaluation_provider_name"
      value: "state.config.provider_name"
      data_type: "str"
      null: False
      max_length: 255

    - name: "evaluation_version"
      data_type: "str"
      value: "config.version"
      null: False
      max_length: 255

    - name: "response_version"
      data_type: "str"
      value: "config.version"
      null: False
      max_length: 255

  embedding:
    - column: "response"
      name: "response_embedding"
      model: "sentence"

    - column: "evaluation_justification"
      name: "evaluation_justification_embedding"
      model: "sentence"

