api = "0.9"
id = "alethic-ism-core.conda-buildpack"
version = "0.1.0"
name = "Alethic ISM Core (Conda Buildpack)"

[metadata]
  include-files = ["bin/detect", "bin/build"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"  # Change this to match your builder’s base stack
