apiVersion: v1
kind: Service
metadata:
  name: superset-service
  namespace: superset
spec:
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8088 
      targetPort: 8088 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-superset
  namespace: superset
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic

    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: superset-basic-auth

    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'

    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - superset.quantumwake.io
      secretName: superset.quantumwake.io
  rules:
    - host: superset.quantumwake.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superset-service
                port:
                  number: 8088 
  ingressClassName: nginx
