package:
  name: alethic-processor
  version: "0.2.0"

source:
  #url: https://github.com/quantumwake/alethic-processor/v0.1.0.tar.gz
  # or use git_rev for a specific branch or commit
  git_url: https://github.com/quantumwake/alethic-processor.git
  git_rev: main

build:
  number: 13
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/quantumwake/alethic-processor
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Instruction Based State Machine - Processors"  # Brief summary of your package
