version: '3.1'

services:
  db:
    container_name: pgvector
    image: ankane/pgvector 
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres1 

        #    volumes:
        #      - type: bind
        #        source: ./static
        #        target: /opt/app/static

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:9000

