# actions.yml

name: Docker Build Python Package using Conda (alethic-ism-core module)

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      id: code_checkout
      uses: actions/checkout@v2

    - name: Assign Environment Variables for Build & Deployment Process
      id: setup_variables

      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | head -c7)
        TAG="krasaee/alethic-ism-api:$COMMIT_ID"
        
        echo "COMMIT_ID=$COMMIT_ID" >> "$GITHUB_ENV" # for local variables
        echo "TAG=$TAG" >> "$GITHUB_ENV" # for local variables

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Package Artifact 
      id: build-conda-package
      run: |
        bash ./docker_build_conda_package.sh
        bash ./docker_extract_conda_package.sh
        
#        echo "checking env file_name: $file_name"
#        echo "::set-output name=file_name::$file_name"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-conda-package.outputs.file_name }}
        path: ${{ steps.build-conda-package.outputs.file_name }}
