name: Docker Build Python Package using Conda (alethic-ism-core module)

on:
  push:
    branches:
      - main

jobs:   
  build-and-upload:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: code_checkout
      uses: actions/checkout@v2

    - name: Assign Environment Variables for Build & Deployment Process
      id: setup_variables

      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | head -c7)
        NAMESPACE="krasaee"
        PROJECT_NAME="alethic-ism-core"
        IMAGE="$NAMESPACE/$PROJECT_NAME:$COMMIT_ID"
        
        echo "COMMIT_ID=$COMMIT_ID" >> "$GITHUB_ENV" # for local variables
        echo "IMAGE=$IMAGE" >> "$GITHUB_ENV" # for local variables
        echo "PYPI_API_KEY=${{ secrets.PYPI_API_KEY }}" >> "$GITHUB_ENV" # for local variables

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Package
      id: build-package
      run: |
        echo "HOME: $HOME"
        echo ${{ secrets.PYPI_API_KEY }} > $HOME/.pypirc
#        sh ./docker_build.sh -t $IMAGE
